### ISSUE TITLE
refactor: teleport method should reset fall distance

### ISSUE THREAD

**Issue by IWareQ** [AllayMC/Allay#517]
This is necessary in order to prevent death from `Chorus Fruit` and `Ender Pearl`

**Comment by IWareQ** [comment]
This [commit](https://github.com/AllayMC/Allay/commit/64fb6ee9e6cd590d1b3f3fc46c68b0716f06c46c) cannot fix this issue.

You can try to execute `/tp ~ 400 ~` and eat `Chorus Fruit` to save yourself from falling, but you will still die because the `teleport()` method takes into account `fallDistance` from 400 height to ~60

**Comment by smartcmd** [comment]
After some research, I found that this is a troublesome problem:

This problem is essentially caused by the desynchronization of data at both ends. Because `PlayerAuthInputPacket` will be sent from the client to the server at a rate of 20 per second. After teleporting, the server still receives the `PlayerAuthInputPacket` sent by the client before teleporting.

The following is a simple simulation (initial player position is (0, 1000, 0)):
```
[C->S] Send PlayerAuthInputPacket with pos (0, 999, 0) `pk1`
[S] Set player pos to ground (0, 100, 0) without fall distance calculation
[S->C] Send new pos (0, 100, 0) `pk2`
[S] Receive `pk1`, set player pos to (0, 999 ,0)
[C] Receive `pk2`, set player pos to (0, 100, 0)
[C->S] Send PlayerAuthInputPacket with pos (0, 100, 0) `pk3`
[S] Receive `pk3`, set player pos from (0, 999, 0) to (0, 100, 0), deltaY=899 -> death
